# Generated by Django 5.2.8 on 2025-11-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=64, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=32, null=True)),
                ('estado', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
